spring:
  security:
    oauth2:
      client:
        registration:
          twitch:
            clientId: ${TWITCH_CLIENT_ID}
            clientSecret: ${TWITCH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: chat:read
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          twitch:
            authorization-uri: https://id.twitch.tv/oauth2/authorize
            token-uri: https://id.twitch.tv/oauth2/token
            user-info-uri: https://id.twitch.tv/oauth2/userinfo
            user-name-attribute: sub
  application:
    name: sentiment