spring:
  security:
    oauth2:
      client:
        registration:
          twitch:
            clientId: ${TWITCH_CLIENT_ID}
            clientSecret: ${TWITCH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: chat:read, clips:edit
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          twitch:
            authorization-uri: https://id.twitch.tv/oauth2/authorize
            token-uri: https://id.twitch.tv/oauth2/token
            user-info-uri: https://id.twitch.tv/oauth2/userinfo
            user-name-attribute: sub
  application:
    name: sentiment
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: example
      authentication-database: admin
#logging:
#  level:
#    org.springframework.web: DEBUG
#    com.nilsson: DEBUG
twitch:
  clip:
    cooldown-time-in-millis: 30000
    scoring-calibration-time-in-millis: 300000